module.exports = {
  apps: [
    {
      name: "bawari-banno",
      cwd: __dirname,
      script: ".output/server/index.mjs",
      interpreter: "node",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        HOST: "0.0.0.0",
        PORT: 3020,
        NITRO_HOST: "0.0.0.0",
        NITRO_PORT: 3020,
        MONGODB_URI: process.env.MONGODB_URI,
        SESSION_SECRET: process.env.SESSION_SECRET,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        PHONEPE_ENV: process.env.PHONEPE_ENV || "production",
        PHONEPE_API_BASE_URL: process.env.PHONEPE_API_BASE_URL,
        PHONEPE_CLIENT_ID: process.env.PHONEPE_CLIENT_ID,
        PHONEPE_CLIENT_SECRET: process.env.PHONEPE_CLIENT_SECRET,
        PHONEPE_MERCHANT_ID: process.env.PHONEPE_MERCHANT_ID,
        PHONEPE_SALT_INDEX: process.env.PHONEPE_SALT_INDEX,
        PHONEPE_SALT_KEY: process.env.PHONEPE_SALT_KEY,
      },
    },
  ],
};
