/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BestsellerRouteImport } from './routes/bestseller'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NewArrivalRouteImport } from './routes/new-arrival'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BestsellerRoute = BestsellerRouteImport.update({
  id: '/bestseller',
  path: '/bestseller',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalRoute = NewArrivalRouteImport.update({
  id: '/new-arrival',
  path: '/new-arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bestseller': typeof BestsellerRoute
  '/contact': typeof ContactRoute
  '/new-arrival': typeof NewArrivalRoute
  '/profile': typeof ProfileRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/trending': typeof TrendingRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bestseller': typeof BestsellerRoute
  '/contact': typeof ContactRoute
  '/new-arrival': typeof NewArrivalRoute
  '/profile': typeof ProfileRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/trending': typeof TrendingRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bestseller': typeof BestsellerRoute
  '/contact': typeof ContactRoute
  '/new-arrival': typeof NewArrivalRoute
  '/profile': typeof ProfileRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/trending': typeof TrendingRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bestseller'
    | '/contact'
    | '/new-arrival'
    | '/profile'
    | '/terms-and-conditions'
    | '/trending'
    | '/wishlist'
    | '/categories/$category'
    | '/products/$productId'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bestseller'
    | '/contact'
    | '/new-arrival'
    | '/profile'
    | '/terms-and-conditions'
    | '/trending'
    | '/wishlist'
    | '/categories/$category'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bestseller'
    | '/contact'
    | '/new-arrival'
    | '/profile'
    | '/terms-and-conditions'
    | '/trending'
    | '/wishlist'
    | '/categories/$category'
    | '/products/$productId'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BestsellerRoute: typeof BestsellerRoute
  ContactRoute: typeof ContactRoute
  NewArrivalRoute: typeof NewArrivalRoute
  ProfileRoute: typeof ProfileRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrendingRoute: typeof TrendingRoute
  WishlistRoute: typeof WishlistRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestseller': {
      id: '/bestseller'
      path: '/bestseller'
      fullPath: '/bestseller'
      preLoaderRoute: typeof BestsellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrival': {
      id: '/new-arrival'
      path: '/new-arrival'
      fullPath: '/new-arrival'
      preLoaderRoute: typeof NewArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BestsellerRoute: BestsellerRoute,
  ContactRoute: ContactRoute,
  NewArrivalRoute: NewArrivalRoute,
  ProfileRoute: ProfileRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrendingRoute: TrendingRoute,
  WishlistRoute: WishlistRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
